name: i_chat
description: IChat Application

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  # lottie
  lottie: ^2.0.0

  # icons
  cupertino_icons: ^1.0.5
  flutter_icons: ^1.1.0
  # bloc: => state manager
  equatable: ^2.0.5
  flutter_bloc: ^8.1.1
  # intl: => date format
  intl: ^0.17.0
  # expandable text
  expandable_text: ^2.3.0
  # firebase
  firebase_auth: ^4.1.1
  firebase_core: ^2.1.1
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.0.4
  # meta: ?
  meta: ^1.8.0
  # get_it: ?
  get_it: ^7.2.0
  # cached_network_image:
  cached_network_image: ^3.2.2
  # flutterToast:
  fluttertoast: ^8.1.1
  # image_picker:
  image_picker: ^0.8.6
  # bubble:
  bubble: ^1.2.1
  # edge_alerts:
  edge_alert: ^0.0.1
  #flutter_svg:
  flutter_svg: ^1.1.6
  # date_format:
  date_format: ^2.0.7

  snapshot: ^0.2.5




dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/AppIcons/
    - assets/lottie_files/

  fonts:
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 700
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Poppins-Thin
      fonts:
        - asset: assets/fonts/Poppins-Thin.ttf
          weight: 700
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 700
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 700

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
